version: "2"
services:
  super-snacks-api:
    container_name: super-snacks-api
    command: bash -c "npm install && npm run start-dev"
    build: .
    volumes:
      - .:/super-snacks-api
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "3000:3000"
  mongo:
    container_name: super-snacks-db
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=super-snacks-db
    volumes:
      - ./.mongo_data:/data/db
    ports:
      - "27017:27017"
